name: stonfi
description: "Stonfi Swap Flutter Sdk."
version: 0.0.5

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  tonutils: ^0.5.6
  http: ^1.2.2
  chopper: ^8.0.1+1
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4
  test: any
  mocktail: ^1.0.4

dependency_overrides:
  build_runner: ^2.4.9
  chopper_generator: ^8.0.1

flutter: